name: Build and Deploy [production]

on:
  [workflow_dispatch]
  
  
env:
  AZURE_WEBAPP_NAME: masterdeploy                                  # set this to your application's name
  AZURE_WEBAPP_URL: https://masterdeploy.azurewebsites.net         # set application url
  AZURE_WEBAPP_PACKAGE_PATH: '.'                                   # set this to the path to your web app project, defaults to the repository root
  NODE_VERSION: '14.x'                                             # set this to the node version to use

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout master from repository
      uses: actions/checkout@master

    ##- name: Login to Azure WebApp
    ##uses: azure/login@v1
    ##with:
    ##creds: ${{ secrets.AZURE_CREDENTIALs }}
    
    - name: Setup Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v1
      with:
       node-version: ${{ env.NODE_VERSION }}

    - name: Run npm install, compile
      run: |
          echo "npm install"
        
    - name: 'Build project'
      if: github.event_name != 'push'
      run: echo "Build the project"
      
    - name: 'Deploy to Production Server'
      if: github.event_name != 'push'
      run: echo "Deploy the project"
