name: merging feature to develop
on:
 pull_request:
  branches: [develop]
 push: 
  branches: [develop]
  

env:
  NODE_VERSION: '14.x'                           # set this to the node version to use

jobs:
  build:
    name: Build 
    runs-on: ubuntu-latest
    environment: develop

    steps:
    - name: Checkout master from repository
      uses: actions/checkout@master
    
    - name: Setup Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v1
      with:
       node-version: ${{ env.NODE_VERSION }}

    - name: Run npm install, compile
      run: |
        echo "npm install"
    
        
    - name: 'Build project'
      if: github.event_name != 'push'
      run: echo "Build the project"
      
    - name: 'Deploy to Staging Server'
      if: github.event_name != 'push'
      run: echo "Deploy the project "
